version: "3"

volumes:
  directus_uploads: {}
  database_data: {}
  database_backups: {}

services:
  backend:
    build:
      context: .
      dockerfile: docker/production/backend/Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - directus_uploads:/directus/uploads
      - database_data:/srv/database
      - database_backups:/srv/database/backups
    networks:
      - kdl
    restart: unless-stopped

networks:
  kdl:
