version: "3"

volumes:
  cms_uploads: {}
  etl_data: {}
  postgres_data: {}
  postgres_backups: {}

services:
  cms:
    build:
      context: .
      dockerfile: docker/production/cms/Dockerfile
    env_file:
      - ./.envs/.cms
    volumes:
      - cms_uploads:/directus/uploads
    depends_on:
      - database
      - cache
    networks:
      - kdl
    restart: unless-stopped

  etl:
    build:
      context: .
      dockerfile: docker/production/etl/Dockerfile
    env_file:
      - ./.envs/.etl
    volumes:
      - etl_data:/srv/app/data
    depends_on:
      - cms
      - database
    networks:
      - kdl

  database:
    image: postgis/postgis:14-master
    env_file:
      - ./.envs/.database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups:/backups
    ports:
      - 5432:5432
    networks:
      - kdl
    restart: unless-stopped

  cache:
    image: redis:6
    networks:
      - kdl
    restart: unless-stopped

networks:
  kdl:
