version: "3"

volumes:
  directus_uploads: {}
  postgres_data: {}
  postgres_backups: {}

services:
  backend:
    build:
      context: .
      dockerfile: docker/production/backend/Dockerfile
    env_file:
      - ./.envs/.backend
    volumes:
      - directus_uploads:/directus/uploads
    depends_on:
      - database
      - cache
    networks:
      - kdl
    restart: unless-stopped

  database:
    image: postgis/postgis:14-master
    env_file:
      - ./.envs/.database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups:/backups
    ports:
      - 5432:5432
    networks:
      - kdl
    restart: unless-stopped

  cache:
    image: redis:6
    networks:
      - kdl
    restart: unless-stopped

networks:
  kdl:
