name: kdl

services:
  proxy:
    image: gitlab.kdl.kcl.ac.uk:5050/docker-images/core/kdl-apache-proxy
    volumes:
      - ../volumes/proxy/pathmap.yml:/maps/pathmap.yaml:ro
    ports:
      - "80:80"
    networks:
      - kdl
    restart: unless-stopped

networks:
  kdl:
